CREATE TABLE IF NOT EXISTS boxscores (
	player text NOT NULL,
	MP text,
    FG text,
    FGA text,
    `3P` text,
    `3PA` text,
    `3P%` text,
    FT  text,
    FTA text,
    `FT%` text,
    ORB text,
    DRB text,
    TRB text,
    AST text,
    STL text,
    BLK text,
    TOV text,
    PF  text,
    PTS text,
    `+/-` text,
    team_name text,
    datetext date,
    unique_id text,
    abbrev text PRIMARY KEY
);